owner: agent-01
repo: upptime
user-agent: agent-01

assignees:
  - agent-01

sites:
  - name: SYOJ
    url: https://syoj.org
  - name: Cloud
    url: https://cloud.xagentx.link
  - name: Home
    url: https://xagentx.link
  - name: OpenWebUI
    url: https://chat.xagentx.link

status-website:
  cname: uptime.xagentx.link
  robotsText: "User-agent: * \n Disallow: /"
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Uptime is powered by Upptime"
  introMessage: "Go to here for more status if it's not down: [Click Me](https://status.xagentx.link)"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

